version: "3"
services:
  core1:
    container_name: core1
    image: "nalim2/sfsc-core"
    ports:
      - "1250:1250"
      - "1251:1251"
      - "1252:1252"
      - "1253:1253"
      - "1254:1254"
      - "5701:5701"
    environment:
      - HOST=127.0.0.1
      - BACKEND_PORT=1250
      - CONTROL_PUB_PORT=1251
      - CONTROL_SUB_PORT=1252
      - DATA_PUB_PORT=1253
      - DATA_SUB_PORT=1254

      - BACKEND_HOST=core1
      - HAZELCAST_PORT=5701

  monitoring-service:
    image: "nalim2/sfsc-plc4x-monitoring:latest"

    environment:
      - EXTERNEL_CORE_IP=core1
      - EXTERNEL_CORE_PORT=1251
      - RUN_MONITORING_SERVICE=true
      - RUN_READ_SERVICE=true
      - RUN_WRITE_SERVICE=false
      - RUN_OPC_EXAMPLE_SERVER=true
    links:
      - core1